# Generated by Django 3.0.2 on 2020-01-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtoon',
            old_name='title_id',
            new_name='list_url',
        ),
    ]
