# Generated by Django 3.0.2 on 2020-01-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0003_auto_20200127_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='ep_num',
        ),
        migrations.AddField(
            model_name='episode',
            name='ep_url',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
