# Generated by Django 3.0.2 on 2020-01-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0004_auto_20200127_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut',
            old_name='src',
            new_name='ep',
        ),
        migrations.AddField(
            model_name='cut',
            name='cut_src',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
